# CMake generated Testfile for 
# Source directory: E:/NUTS/libarchive-3.4.3/cat/test
# Build directory: E:/NUTS/libarchive-3.4.3/cat/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_0 "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_0")
  set_tests_properties(bsdcat_test_0 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;1;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_0 "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_0")
  set_tests_properties(bsdcat_test_0 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;1;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_0 "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_0")
  set_tests_properties(bsdcat_test_0 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;1;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_0 "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_0")
  set_tests_properties(bsdcat_test_0 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;1;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_0 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_empty_gz "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_gz")
  set_tests_properties(bsdcat_test_empty_gz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;2;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_empty_gz "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_gz")
  set_tests_properties(bsdcat_test_empty_gz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;2;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_empty_gz "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_gz")
  set_tests_properties(bsdcat_test_empty_gz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;2;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_empty_gz "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_gz")
  set_tests_properties(bsdcat_test_empty_gz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;2;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_empty_gz NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_empty_lz4 "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_lz4")
  set_tests_properties(bsdcat_test_empty_lz4 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;3;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_empty_lz4 "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_lz4")
  set_tests_properties(bsdcat_test_empty_lz4 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;3;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_empty_lz4 "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_lz4")
  set_tests_properties(bsdcat_test_empty_lz4 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;3;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_empty_lz4 "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_lz4")
  set_tests_properties(bsdcat_test_empty_lz4 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;3;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_empty_lz4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_empty_xz "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_xz")
  set_tests_properties(bsdcat_test_empty_xz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;4;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_empty_xz "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_xz")
  set_tests_properties(bsdcat_test_empty_xz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;4;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_empty_xz "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_xz")
  set_tests_properties(bsdcat_test_empty_xz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;4;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_empty_xz "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_xz")
  set_tests_properties(bsdcat_test_empty_xz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;4;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_empty_xz NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_empty_zstd "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_zstd")
  set_tests_properties(bsdcat_test_empty_zstd PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;5;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_empty_zstd "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_zstd")
  set_tests_properties(bsdcat_test_empty_zstd PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;5;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_empty_zstd "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_zstd")
  set_tests_properties(bsdcat_test_empty_zstd PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;5;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_empty_zstd "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_empty_zstd")
  set_tests_properties(bsdcat_test_empty_zstd PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;5;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_empty_zstd NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_error "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_error")
  set_tests_properties(bsdcat_test_error PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;6;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_error "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_error")
  set_tests_properties(bsdcat_test_error PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;6;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_error "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_error")
  set_tests_properties(bsdcat_test_error PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;6;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_error "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_error")
  set_tests_properties(bsdcat_test_error PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;6;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_error NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_error_mixed "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_error_mixed")
  set_tests_properties(bsdcat_test_error_mixed PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;7;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_error_mixed "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_error_mixed")
  set_tests_properties(bsdcat_test_error_mixed PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;7;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_error_mixed "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_error_mixed")
  set_tests_properties(bsdcat_test_error_mixed PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;7;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_error_mixed "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_error_mixed")
  set_tests_properties(bsdcat_test_error_mixed PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;7;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_error_mixed NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_Z "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_Z")
  set_tests_properties(bsdcat_test_expand_Z PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;8;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_Z "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_Z")
  set_tests_properties(bsdcat_test_expand_Z PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;8;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_Z "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_Z")
  set_tests_properties(bsdcat_test_expand_Z PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;8;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_Z "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_Z")
  set_tests_properties(bsdcat_test_expand_Z PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;8;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_expand_Z NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_bz2 "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_bz2")
  set_tests_properties(bsdcat_test_expand_bz2 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;9;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_bz2 "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_bz2")
  set_tests_properties(bsdcat_test_expand_bz2 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;9;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_bz2 "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_bz2")
  set_tests_properties(bsdcat_test_expand_bz2 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;9;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_bz2 "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_bz2")
  set_tests_properties(bsdcat_test_expand_bz2 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;9;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_expand_bz2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_gz "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_gz")
  set_tests_properties(bsdcat_test_expand_gz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;10;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_gz "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_gz")
  set_tests_properties(bsdcat_test_expand_gz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;10;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_gz "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_gz")
  set_tests_properties(bsdcat_test_expand_gz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;10;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_gz "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_gz")
  set_tests_properties(bsdcat_test_expand_gz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;10;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_expand_gz NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_lz4 "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_lz4")
  set_tests_properties(bsdcat_test_expand_lz4 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;11;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_lz4 "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_lz4")
  set_tests_properties(bsdcat_test_expand_lz4 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;11;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_lz4 "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_lz4")
  set_tests_properties(bsdcat_test_expand_lz4 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;11;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_lz4 "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_lz4")
  set_tests_properties(bsdcat_test_expand_lz4 PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;11;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_expand_lz4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_mixed "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_mixed")
  set_tests_properties(bsdcat_test_expand_mixed PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;12;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_mixed "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_mixed")
  set_tests_properties(bsdcat_test_expand_mixed PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;12;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_mixed "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_mixed")
  set_tests_properties(bsdcat_test_expand_mixed PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;12;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_mixed "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_mixed")
  set_tests_properties(bsdcat_test_expand_mixed PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;12;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_expand_mixed NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_plain "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_plain")
  set_tests_properties(bsdcat_test_expand_plain PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;13;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_plain "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_plain")
  set_tests_properties(bsdcat_test_expand_plain PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;13;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_plain "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_plain")
  set_tests_properties(bsdcat_test_expand_plain PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;13;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_plain "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_plain")
  set_tests_properties(bsdcat_test_expand_plain PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;13;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_expand_plain NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_xz "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_xz")
  set_tests_properties(bsdcat_test_expand_xz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;14;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_xz "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_xz")
  set_tests_properties(bsdcat_test_expand_xz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;14;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_xz "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_xz")
  set_tests_properties(bsdcat_test_expand_xz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;14;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_xz "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_xz")
  set_tests_properties(bsdcat_test_expand_xz PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;14;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_expand_xz NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_zstd "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_zstd")
  set_tests_properties(bsdcat_test_expand_zstd PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;15;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_zstd "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_zstd")
  set_tests_properties(bsdcat_test_expand_zstd PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;15;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_zstd "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_zstd")
  set_tests_properties(bsdcat_test_expand_zstd PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;15;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_zstd "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_expand_zstd")
  set_tests_properties(bsdcat_test_expand_zstd PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;15;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_expand_zstd NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_help "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_help")
  set_tests_properties(bsdcat_test_help PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;16;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_help "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_help")
  set_tests_properties(bsdcat_test_help PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;16;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_help "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_help")
  set_tests_properties(bsdcat_test_help PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;16;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_help "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_help")
  set_tests_properties(bsdcat_test_help PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;16;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_help NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_stdin "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_stdin")
  set_tests_properties(bsdcat_test_stdin PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;17;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_stdin "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_stdin")
  set_tests_properties(bsdcat_test_stdin PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;17;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_stdin "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_stdin")
  set_tests_properties(bsdcat_test_stdin PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;17;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_stdin "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_stdin")
  set_tests_properties(bsdcat_test_stdin PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;17;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_stdin NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_version "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Debug/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_version")
  set_tests_properties(bsdcat_test_version PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;18;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_version "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/Release/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_version")
  set_tests_properties(bsdcat_test_version PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;18;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_version "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/MinSizeRel/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_version")
  set_tests_properties(bsdcat_test_version PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;18;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_version "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "E:/NUTS/libarchive-3.4.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "E:/NUTS/libarchive-3.4.3/cat/test" "test_version")
  set_tests_properties(bsdcat_test_version PROPERTIES  _BACKTRACE_TRIPLES "E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;59;ADD_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;18;DEFINE_TEST;E:/NUTS/libarchive-3.4.3/cat/test/list.h;0;;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;67;INCLUDE;E:/NUTS/libarchive-3.4.3/cat/test/CMakeLists.txt;0;")
else()
  add_test(bsdcat_test_version NOT_AVAILABLE)
endif()
